/**
 * Data shapes the materials + pricing pipeline works on.
 *
 * These used to live in src/types/index.ts. They moved here so the pipeline
 * core (shared/pricing/pipeline.ts) can run on the phone AND inside a Cloud
 * Function from one definition — the app re-exports every one of them from
 * src/types, so nothing in the app imports this file directly.
 *
 * Rule for this directory: import only from within shared/. A relative path
 * into src/ resolves differently from the functions package's symlinked copy
 * (functions/src/shared → ../../shared) and breaks one build or the other.
 */

export interface Material {
  id: string;
  name: string;
  quantity: number;
  unit: 'each' | 'm' | 'm²' | 'm³' | 'L' | 'kg' | 'box' | 'pack';
  // True underlying requirement before pack rounding. When the priced product
  // is sold in packs (e.g. box of 500 screws, 5.4m timber length), the LLM
  // emits the per-unit need here and `quantity` is the rounded-up pack count
  // the tradie actually buys. totalPrice = quantity * price stays correct.
  requiredQty?: number;
  // The unit requiredQty is stated in — the material's ORIGINAL unit before
  // pack conversion mutates `unit` to a purchase unit. Without it, an
  // each-requirement priced against a length SKU (7 posts, 2.4m each) is
  // unrecoverable: packUnit says 'm' but requiredQty means 7 posts, and
  // consumers that read requiredQty in packUnit under-buy 3×.
  requiredUnit?: Material['unit'];
  // Set when a priced product is a multi-unit pack/length. packSize is in
  // packUnit (e.g. 500 each, 5.4 m, 20 m). Used to recompute quantity from
  // requiredQty whenever the price source changes.
  packSize?: number;
  packUnit?: Material['unit'];
  bunningsItemNumber?: string;
  /**
   * Product identities (item numbers / product URLs) this row must never be
   * matched to again. Written by the reprice wipe when a match kept coming
   * back with implausible money (QU-178763's $187.25 twins re-priced to the
   * exact same $187.25 — the ranking is deterministic, so without exclusion
   * a re-fetch can only re-pick the same wrong product). Read by
   * pickBestCandidate via the pipeline's excludeProducts option.
   */
  excludedProducts?: string[];
  // Reece-specific identifiers, populated when pricingSource is the Reece API.
  // Both are required to build a valid /au/order-gateway/orders payload, so
  // the "Order from Reece" button only enables when these are present on at
  // least one material.
  reeceItemNumber?: string;       // matches productId from Reece's product-gateway/search
  reeceUnitOfMeasure?: string;    // e.g. "LEN", "MTR" — matches the pack from search.unitOfMeasures[]
  price: number; // per unit
  totalPrice: number;
  manualPriceOverride: boolean;
  searchTerm?: string;
  productUrl?: string; // Link to the actual product page
  favoriteProduct?: FavoriteProductMapping; // User's preferred product for this material
  // How this line item entered the quote: 'recommended' = generated by the
  // "Get Recommended Gear" pipeline from the job scope; 'manual' = added or
  // edited by the tradie. Captured for pipeline telemetry/review — no UI hangs
  // off it yet. Stamped once at creation and never overwritten (see withOrigin).
  origin?: 'recommended' | 'manual';
  // Pricing and product metadata
  pricingSource?: 'scraper' | 'api' | 'ai' | 'manual'; // Where the price came from
  priceConfidence?: 'high' | 'medium' | 'low'; // AI price confidence level
  // The priced product barely resembles what we searched for — a lexical
  // near-miss the supplier still returned (see utils/matchEvidence.ts). The
  // price is real, but it may be a real price for the WRONG product, so this
  // gates the send rather than just tinting the row. Cleared on a re-price
  // that lands a proper match.
  weakProductMatch?: boolean;
  // Snapshot of the row as the pricing pipeline last left it (see
  // utils/asPriced.ts). Send-time telemetry diffs the sent row against this
  // to log tradie corrections — confirmed pipeline misses. Absent on
  // hand-priced rows and quotes priced before this field shipped.
  asPriced?: {
    price: number;
    quantity: number;
    name: string;
    pricingSource?: Material['pricingSource'];
    priceConfidence?: Material['priceConfidence'];
  };
  imageUrl?: string; // Product image URL
  description?: string; // Product description
  /**
   * What this line *is*. Absent/'material' = a priced product with a real
   * quantity and unit price. 'work' = a lump-sum scope line: a title, a scope
   * paragraph, and one price. quantity is forced to 1 and unit to 'each' so
   * totalPrice = quantity × price still holds and every existing calculator,
   * adapter and Xero mapper works unchanged.
   *
   * Markup does NOT apply to a work item. The field says "Line total" and the
   * tradie typed a final price into it, so charging the customer more than that
   * would be the app inventing a number nobody chose. This is the same rule
   * `QuoteSection.pricing: 'lumpSum'` follows, and it lives in exactly one
   * place — shared/document/lumpSum.ts. Every money path resolves the
   * multiplier PER LINE through `lineMarkupMultiplier`; a real material still
   * takes markup normally, because that is a margin on a supplier price the
   * tradie didn't set.
   */
  kind?: 'material' | 'work';
  /**
   * Customer-facing scope paragraph, newline-separated. Deliberately NOT
   * `description` — the pricing pipeline OWNS that field and overwrites it at
   * 15 sites in materialsPipeline.ts with verdicts like "Not a retail item
   * (service/supply) — add your price before sending". Reusing `description`
   * would silently destroy the tradie's scope text on the next reprice.
   */
  scope?: string;
  brand?: string; // Product brand
  stockLevel?: string; // Stock availability (deprecated, use stockCheckedAt)
  stockCheckedAt?: string; // ISO timestamp of when stock was last checked
  // Material categorization
  category?: string; // Trade category ID (e.g., 'carpentry', 'electrical', 'plumbing')
  section?: string; // Work section within a job (e.g., 'Concreting', 'Timber Framing')
  templateBaseQuantity?: number; // Per-unit qty from template/AI (e.g. 2 posts per bay). quantity = templateBaseQuantity * section.multiplier
  // Detected quality tier from the job description (e.g. "high quality",
  // "premium fittings", "budget reno"). Used by candidateRanker to pick
  // the right price band out of the supplier search results instead of
  // always taking the first/cheapest hit. Inherited from the job-level
  // qualityTier on the Quote when not set per-material.
  qualityTier?: 'budget' | 'standard' | 'premium';
  // How this material's quantity relates to floorplan geometry, when the
  // quantity was grounded on an attached plan. Lets the backend deterministically
  // re-scale the quantity if the takeoff is anchored to a stated dimension.
  planBasis?: 'area' | 'perimeter' | 'volume' | 'fixed';
  // Set true when scaleMaterialsToAnchor adjusted this quantity to a stated anchor.
  quantityScaledToAnchor?: boolean;
}

export interface FavoriteProductMapping {
  productName: string;
  store: string;
  productUrl?: string;
  itemNumber?: string;
  dimensions?: string;
  unit?: Material['unit'];
  price?: number; // Last known price
  imageUrl?: string; // Product image
  // Personal supplier rate fields
  isPersonalRate?: boolean;       // true → prefer over retail in auto-generate
  coveragePerUnit?: number;       // 1 unit covers N of coverageUnit (e.g. 13 m² per sheet)
  coverageUnit?: 'm²' | 'm³' | 'm';
  keywords?: string[];            // ["concrete","slab","footing"] for LLM matching
  notes?: string;
  // Provenance — PR1: 'manual', PR2: 'imported', PR3: 'subscribed'
  source?: 'manual' | 'imported' | 'subscribed';
  sourceRef?: string;             // PR2: importBatchId | PR3: supplierListId
  lastUpdatedAt?: string;         // ISO timestamp
}

// A single measurable region read off a plan. Deliberately trade-agnostic —
// "zone" (not "finish code") so the same shape serves flooring, tiling,
// painting, concreting, landscaping, etc. `code` carries a plan label when one
// is printed (FC01, R1, Room 3…) but is never required.
export interface FloorplanZone {
  label: string;          // human label, e.g. "Master bedroom" or "FC01 area"
  code?: string;          // plan-printed code if any (FC01, R1, …)
  areaM2?: number;
  // Zone boundary length and the total width of doorways/openings in it.
  // Net edge (perimeterM - openingsDeductionM) drives skirting/coving/edging
  // lineal metres for zones where the finish needs edge treatment.
  perimeterM?: number;
  openingsDeductionM?: number;
  removalAreaM2?: number; // strip-out / demolition scope for this zone
  dims?: { lengthM: number; widthM: number };
}

// Structured geometry extracted from an architectural plan/drawing in the photo
// pipeline. Always carries `assumptions` + `confidence` so a misread surfaces to
// the user instead of being silently baked into quantities.
export interface FloorplanAnalysis {
  detected: boolean;
  scale?: string;                 // "1:100"
  calibration?: {
    source: 'scale_bar' | 'known_dimension' | 'stated_total';
    basisMm?: number;             // the reference length used to set scale
    statedLengthMm?: number;      // tradie-stated overall length, echoed for the anchor
    note: string;
  };
  // Outer bounding-box dimensions the model measured for the whole plan.
  footprintDims?: { lengthM: number; widthM: number };
  totalAreaM2?: number;
  perimeterM?: number;            // drives skirting / edging / cornice / kerb
  zones?: FloorplanZone[];
  removalAreaM2?: number;         // strip-out / demolition scope
  removalBinM3?: number;          // estimated waste skip volume
  // Whether the takeoff was rescaled onto a user-stated/known real-world
  // dimension, and the linear factor applied.
  scaledToAnchor?: boolean;
  scaleFactorApplied?: number;
  // 'model' = measured/derived, 'user' = manually corrected.
  source?: 'model' | 'user';
  // User-edited overrides — when present these win over the measured values.
  // Model fields are never overwritten, so re-analysis can't wipe a correction
  // and the card can show "measured → corrected".
  corrected?: {
    totalAreaM2?: number;
    perimeterM?: number;
    removalBinM3?: number;
    // Area factor applied to the model's zone areas when the user accepted
    // "scale the other areas to match" after correcting the total. Zones stay
    // stored as measured; this scales them at read time (lengths by its √).
    zonesScaledBy?: number;
    editedAt?: string;
  };
  assumptions: string;            // what was inferred or could not be read
  confidence: 'low' | 'medium' | 'high';
}

// Labor unit type for hours/days billing
export type LaborUnit = 'hours' | 'days';

/**
 * The unit labour is STORED in — hours, and only hours. Days are a display
 * choice (`labourDisplayUnit`), never a storage one.
 *
 * This is a distinct type from LaborUnit so the compiler refuses any attempt to
 * write a day-shaped quote or invoice. Legacy records still arrive with
 * `laborUnit: 'days'`; they are converted on read by normaliseLabourToHours,
 * which takes a loose input shape precisely so it can accept them. If you find
 * yourself wanting to widen this back to LaborUnit, read the header of
 * shared/document/labourUnits.ts first — storing two units is what produced
 * quotes at 8× and 64× the tradie's rate.
 */
export type StoredLabourUnit = 'hours';

// Section within a quote/invoice with its own labor
export interface QuoteSection {
  id: string;
  name: string;               // e.g. "Colorbond Fence Bay", "Pedestrian Gate"
  multiplier: number;          // How many units (e.g. 8 bays) — default 1
  sourceTemplateId?: string;   // Which template this came from (if any)
  laborHours: number;          // Per-unit labor HOURS (canonical — see shared/document/labourUnits.ts)
  // Total labor hours for the section (laborHours × multiplier).
  // Persisted so consumers that don't know about multipliers (admin
  // dashboard, third-party integrations) can render the right number
  // without any math. The mobile app reads this for display; pricing
  // still derives from laborHours × multiplier × laborRate to match how
  // the editor adjusts per-unit values.
  laborHoursTotal?: number;
  laborRate: number;           // $/HOUR (canonical)
  laborUnit: StoredLabourUnit; // Always 'hours' — see StoredLabourUnit
  laborTotal: number;          // calculated: laborHours * laborRate * multiplier
  sortOrder: number;
  /**
   * 'hourly' (default / legacy undefined) — laborTotal is DERIVED from
   *   laborHours × laborRate × multiplier. Editors may recompute it.
   * 'lumpSum' — laborTotal is a number the TRADIE TYPED. laborHours and
   *   laborRate are 0 and mean nothing. No editor, healer, integrity check
   *   or markup pass may recompute or redistribute it.
   *
   * The invariant, locked by test: for 'lumpSum',
   *   laborHours === 0 && laborHoursTotal === 0 && laborRate === 0.
   * Zeroing the hours is what lets every hours-summing consumer stay correct
   * without knowing this flag exists.
   */
  pricing?: 'hourly' | 'lumpSum';
  /** Customer-facing scope text for this section. Multi-line, reaches the PDF. */
  description?: string;
}

// Reusable section template (assembly)
export interface SectionTemplate {
  id: string;
  name: string;                // e.g. "Standard Fence Bay"
  description?: string;
  keywords?: string[];         // e.g. ["fence bay", "colorbond fence"] — for matching to job descriptions
  materials: Omit<Material, 'id'>[];  // Template materials (IDs generated on use)
  laborHours: number;
  laborRate: number;
  laborUnit: LaborUnit;
  createdAt: string;
  updatedAt: string;
}

// User-defined supplier group for materials search
export interface SupplierGroup {
  id: string;
  name: string;              // e.g. "Local Timber Yard", "Fencing Supplies Co"
  searchUrl?: string;        // Optional base URL for web scraping
  isDefault?: boolean;       // Built-in groups (Bunnings, Reece) can't be deleted
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
  // Optional contact details — surfaced in the supplier book card
  contactPerson?: string;    // Account manager / rep name
  phone?: string;
  email?: string;
  address?: string;
  notes?: string;
}

// Embedded job descriptor that lives inside a Quote/Invoice/Document. Pre-dates
// the top-level Job entity introduced in Phase 8 — renamed to JobSpec to free
// the name for the new top-level Job re-exported below.
export interface JobSpec {
  id: string;
  name: string;
  description: string;
  template?: 'stairs' | 'deck' | 'fence' | 'pergola' | 'custom';
  estimatedHours?: number;
  customParams?: Record<string, number>; // e.g., { steps: 15, length: 10 }
  // Geometry read off an attached plan during gear generation (area, perimeter,
  // per-zone breakdown). Present only when a floorplan/drawing was detected.
  floorplanAnalysis?: FloorplanAnalysis;
}
