#!/bin/bash

echo "================================================"
echo "Download EAS Keystore - Interactive Helper"
echo "================================================"
echo ""
echo "This script will help you download your keystore from EAS."
echo ""
echo "Run the following command and follow the prompts:"
echo ""
echo "  npx eas-cli credentials"
echo ""
echo "Steps to follow:"
echo "  1. Select: Android"
echo "  2. Select: production (or your build profile)"
echo "  3. Choose: Keystore: Manage everything needed to build your project"
echo "  4. Select: Download credentials"
echo "  5. Save to: android/app/upload.keystore"
echo ""
echo "After downloading, the keystore info will be displayed."
echo "You'll need to update android/app/build.gradle with:"
echo "  - storeFile"
echo "  - storePassword"
echo "  - keyAlias"
echo "  - keyPassword"
echo ""
echo "================================================"
echo ""

read -p "Press Enter to launch EAS credentials manager..."

npx eas-cli credentials

echo ""
echo "================================================"
echo "Next steps after downloading:"
echo "================================================"
echo ""
echo "1. Verify the keystore SHA1 matches what Google expects:"
echo "   keytool -list -v -keystore android/app/upload.keystore"
echo ""
echo "   Expected SHA1: A1:61:C6:5E:E2:9B:51:16:27:87:6E:EF:D9:3B:FC:8E:8D:BD:A2:E7"
echo ""
echo "2. Update android/app/build.gradle with the signing config"
echo ""
echo "3. Build locally with:"
echo "   cd android && ./gradlew bundlePlayRelease"
echo ""
