// Maps a proposal id to the real Firestore quote id it minted on Apply.
//
// Why this exists: when Mate emits propose_draft_quote the model only sees
// `{ ok: true, proposalId }` — the real quote id doesn't exist yet, because it's
// minted client-side when the tradie taps Apply. The model routinely conflates
// the two and later calls get_quote / review_quote / propose_reprice /
// propose_delete_line_item with the PROPOSAL id instead of the minted quote id.
// That lookup 404s ("Quote not found") and Mate tells the tradie something went
// wrong fetching the quote.
//
// The minted id is also pushed back as a "[context]" note, but that channel is
// voice-only (the text path is single-shot with no live session), isn't
// persisted, and competes with the proposalId the model already has. This map is
// the durable fallback: Apply records proposalId -> quoteId here, and every tool
// that takes a quoteId resolves through resolveQuoteId() first. A proposal-shaped
// argument transparently becomes the real quote id; anything else passes through
// untouched.

const PROPOSAL_ID_PREFIX = 'prop_';
// Bound the map so a long-running session can't grow it without limit. Insertion
// order is preserved, so the oldest mapping is evicted first.
const MAX_ENTRIES = 50;

const proposalToQuote = new Map<string, string>();

/** True for ids generated by proposalTools.newProposalId() (`prop_…`). */
export function isProposalId(id: string | undefined | null): boolean {
  return String(id || '').startsWith(PROPOSAL_ID_PREFIX);
}

/**
 * Record that a proposal was applied and minted a quote. Call after a
 * successful Apply, once the real quote id is known.
 */
export function rememberAppliedQuote(proposalId: string | undefined, quoteId: string | undefined): void {
  if (!proposalId || !quoteId) return;
  if (!isProposalId(proposalId)) return;
  // Re-insert so this key counts as most-recently-used for eviction.
  proposalToQuote.delete(proposalId);
  proposalToQuote.set(proposalId, quoteId);
  while (proposalToQuote.size > MAX_ENTRIES) {
    const oldest = proposalToQuote.keys().next().value;
    if (oldest === undefined) break;
    proposalToQuote.delete(oldest);
  }
}

/**
 * Translate a proposal id to the quote id it minted. Real quote ids (and
 * unknown proposal ids) are returned unchanged so callers can still run their
 * own not-found handling.
 */
export function resolveQuoteId(id: string | undefined | null): string {
  const raw = String(id || '');
  if (!isProposalId(raw)) return raw;
  return proposalToQuote.get(raw) || raw;
}
