const { withAndroidStyles, createRunOncePlugin } = require("@expo/config-plugins");

/**
 * Paint the Android window navy so the launch never flashes a blank frame.
 *
 * MainActivity launches under `Theme.App.SplashScreen`, whose windowBackground
 * is the navy splash drawable. In onCreate it swaps to `AppTheme`, which
 * declares no windowBackground at all — so the window falls back to whatever
 * `Theme.EdgeToEdge` inherits, `?android:colorBackground`. That is white on a
 * light-mode phone and Material dark grey on a dark-mode one. Between the theme
 * swap and React's first frame there is nothing else to draw, so the user sees
 * that colour full-screen.
 *
 * Measured on an API 36 emulator, 6 Sep 2026: a 0.8s white screen between the
 * navy splash and the app on a light-mode device, and the same gap in dark grey
 * with the emulator in dark mode — which is what proves it is the window
 * background rather than anything React renders.
 *
 * `@color/splashscreen_background` is the same #1E293B as the splash drawable,
 * the iOS SplashScreenBackground colorset and SplashOverlay — see the colour
 * invariant note in app.config.js. Setting it here means the window is already
 * the splash colour when the drawable goes away, so the native → JS handoff has
 * no seam to show.
 *
 * android/ is gitignored and regenerated by prebuild, so this can only live in
 * a config plugin. It ships in a native binary, not an OTA.
 */
const WINDOW_BACKGROUND = "android:windowBackground";
const SPLASH_COLOR_REF = "@color/splashscreen_background";

/**
 * Pure transform over the parsed styles object, so the item can be asserted
 * without running a prebuild. Same exported-helper shape as
 * withPredictiveBackOptOut's disablePredictiveBack.
 */
function setAppThemeWindowBackground(styles) {
  const { assignStylesValue, getAppThemeGroup } = require("@expo/config-plugins").AndroidConfig.Styles;
  return assignStylesValue(styles, {
    add: true,
    parent: getAppThemeGroup(),
    name: WINDOW_BACKGROUND,
    value: SPLASH_COLOR_REF,
  });
}

function withAndroidWindowBackground(config) {
  return withAndroidStyles(config, (config) => {
    config.modResults = setAppThemeWindowBackground(config.modResults);
    return config;
  });
}

module.exports = createRunOncePlugin(
  withAndroidWindowBackground,
  "withAndroidWindowBackground",
  "1.0.0"
);
module.exports.setAppThemeWindowBackground = setAppThemeWindowBackground;
module.exports.WINDOW_BACKGROUND = WINDOW_BACKGROUND;
module.exports.SPLASH_COLOR_REF = SPLASH_COLOR_REF;
