/**
 * Regression tests for the Gradle heap bump.
 *
 * Adding @livekit/react-native-webrtc made :app:mergeExtDexDebug run out of
 * Java heap under Expo's default -Xmx2048m. The failure surfaces as a
 * DexArchiveMergerException, which reads like a duplicate-class or library
 * incompatibility and is neither — so the value of pinning this is as much
 * about not re-diagnosing it as about the build passing.
 *
 * android/gradle.properties is gitignored and regenerated by prebuild, so the
 * replace path (not the append path) is the one that runs in practice.
 */
import { describe, it, expect } from 'vitest';

// eslint-disable-next-line @typescript-eslint/no-var-requires
const { setJvmArgs, DEFAULT_JVM_ARGS } = require('./withGradleJvmArgs');

type Item =
  | { type: 'property'; key: string; value: string }
  | { type: 'comment'; value: string }
  | { type: 'empty' };

// What Expo's prebuild template actually emits.
const TEMPLATE: Item[] = [
  { type: 'comment', value: 'Project-wide Gradle settings.' },
  { type: 'property', key: 'org.gradle.jvmargs', value: '-Xmx2048m -XX:MaxMetaspaceSize=512m' },
  { type: 'empty' },
  { type: 'property', key: 'android.useAndroidX', value: 'true' },
  { type: 'property', key: 'newArchEnabled', value: 'true' },
];

const jvmArgsOf = (items: Item[]) =>
  items.find((i): i is Extract<Item, { type: 'property' }> =>
    i.type === 'property' && i.key === 'org.gradle.jvmargs')?.value;

describe('setJvmArgs', () => {
  it('replaces the template 2048m heap with the larger default', () => {
    expect(jvmArgsOf(TEMPLATE)).toBe('-Xmx2048m -XX:MaxMetaspaceSize=512m');
    const out = setJvmArgs(TEMPLATE);
    expect(jvmArgsOf(out)).toBe(DEFAULT_JVM_ARGS);
  });

  it('asks for more heap than the Expo default that failed the dex merge', () => {
    const mb = Number(/-Xmx(\d+)m/.exec(DEFAULT_JVM_ARGS)![1]);
    expect(mb).toBeGreaterThan(2048);
  });

  it('appends the property when the template has no jvmargs line at all', () => {
    const withoutJvmArgs = TEMPLATE.filter(
      (i) => !(i.type === 'property' && i.key === 'org.gradle.jvmargs'),
    );
    const out = setJvmArgs(withoutJvmArgs);
    expect(jvmArgsOf(out)).toBe(DEFAULT_JVM_ARGS);
  });

  it('leaves every other property untouched', () => {
    const out = setJvmArgs(TEMPLATE);
    const newArch = out.find((i: Item) => i.type === 'property' && i.key === 'newArchEnabled');
    expect(newArch).toEqual({ type: 'property', key: 'newArchEnabled', value: 'true' });
    expect(out).toHaveLength(TEMPLATE.length);
  });

  it('does not mutate the input array', () => {
    const snapshot = JSON.parse(JSON.stringify(TEMPLATE));
    setJvmArgs(TEMPLATE);
    expect(TEMPLATE).toEqual(snapshot);
  });

  it('honours an explicit override', () => {
    const out = setJvmArgs(TEMPLATE, '-Xmx8192m');
    expect(jvmArgsOf(out)).toBe('-Xmx8192m');
  });
});
