const { withAndroidManifest, createRunOncePlugin } = require("@expo/config-plugins");

/**
 * Keep the Android back button (and back gesture) reaching React Navigation
 * on Android 16.
 *
 * targetSdk 36 — required by Play since 31 Aug 2026, see app.config.js — turns
 * Android 16's predictive-back dispatch on by default. In that mode the OS no
 * longer calls Activity.onBackPressed and no longer delivers KEYCODE_BACK; it
 * expects the app to have registered an OnBackInvokedCallback instead. React
 * Native 0.79 registers none (its BackHandler is fed from onBackPressed — grep
 * ReactAndroid for OnBackInvoked and you get nothing), so on an Android 16
 * device every back press falls through to the system default, which finishes
 * the activity. Symptom: back on any screen leaves the app instead of popping
 * the stack, closing a sheet, or returning to the Dashboard tab.
 *
 * Verified on an API 36 emulator with release builds of 1.56, 2 Sep 2026: without
 * the attribute a JS hardwareBackPress listener never fires and the app exits;
 * with it the listener fires and the app stays put.
 *
 * android:enableOnBackInvokedCallback="false" on <application> is Android's
 * documented opt-out for apps that haven't migrated, and unlike edge-to-edge it
 * is still honoured at targetSdk 36. It goes on <application> rather than the
 * activity so SDK-owned activities (Square, Google sign-in) get the legacy
 * dispatch too.
 *
 * Remove once React Native registers its own OnBackInvokedCallback. android/
 * is gitignored and regenerated by prebuild, so the attribute can only live
 * here.
 */
const ENABLE_ON_BACK_INVOKED_CALLBACK = "android:enableOnBackInvokedCallback";

/**
 * Pure transform over the parsed manifest object, so the attribute can be
 * asserted without running a prebuild. Same exported-helper shape as
 * withLiveKitManifestTrim's trimScreenShare.
 */
function disablePredictiveBack(androidManifest) {
  const application = (androidManifest.manifest.application || [])[0];
  if (!application) return androidManifest;
  application.$ = application.$ || {};
  application.$[ENABLE_ON_BACK_INVOKED_CALLBACK] = "false";
  return androidManifest;
}

function withPredictiveBackOptOut(config) {
  return withAndroidManifest(config, (config) => {
    config.modResults = disablePredictiveBack(config.modResults);
    return config;
  });
}

module.exports = createRunOncePlugin(
  withPredictiveBackOptOut,
  "withPredictiveBackOptOut",
  "1.0.0"
);
module.exports.disablePredictiveBack = disablePredictiveBack;
module.exports.ENABLE_ON_BACK_INVOKED_CALLBACK = ENABLE_ON_BACK_INVOKED_CALLBACK;
