// Core data models for QuoteMate

// PDF Template types (imported from shared module for local use, re-exported for consumers)
import type { PdfTemplateId, PdfTemplateInfo } from '../../shared/pdf/types';
export type { PdfTemplateId, PdfTemplateInfo };

// Delivery-channel enum shared with the unified Document model.
import type { SendMethod } from '../../shared/document/types';
export type { SendMethod };

// Record of a customer accepting the business's T&Cs at payment time.
// Stamped on the quote/invoice doc so the version they paid under is auditable.
export interface TcAcceptance {
  versionHash: string;          // hash of the T&Cs text snapshot at send time
  at: Date;                     // when the acceptance was recorded
  source: 'pay_link' | 'tap_to_pay' | 'manual';
}

export interface Material {
  id: string;
  name: string;
  quantity: number;
  unit: 'each' | 'm' | 'm²' | 'm³' | 'L' | 'kg' | 'box' | 'pack';
  // True underlying requirement before pack rounding. When the priced product
  // is sold in packs (e.g. box of 500 screws, 5.4m timber length), the LLM
  // emits the per-unit need here and `quantity` is the rounded-up pack count
  // the tradie actually buys. totalPrice = quantity * price stays correct.
  requiredQty?: number;
  // The unit requiredQty is stated in — the material's ORIGINAL unit before
  // pack conversion mutates `unit` to a purchase unit. Without it, an
  // each-requirement priced against a length SKU (7 posts, 2.4m each) is
  // unrecoverable: packUnit says 'm' but requiredQty means 7 posts, and
  // consumers that read requiredQty in packUnit under-buy 3×.
  requiredUnit?: Material['unit'];
  // Set when a priced product is a multi-unit pack/length. packSize is in
  // packUnit (e.g. 500 each, 5.4 m, 20 m). Used to recompute quantity from
  // requiredQty whenever the price source changes.
  packSize?: number;
  packUnit?: Material['unit'];
  bunningsItemNumber?: string;
  // Reece-specific identifiers, populated when pricingSource is the Reece API.
  // Both are required to build a valid /au/order-gateway/orders payload, so
  // the "Order from Reece" button only enables when these are present on at
  // least one material.
  reeceItemNumber?: string;       // matches productId from Reece's product-gateway/search
  reeceUnitOfMeasure?: string;    // e.g. "LEN", "MTR" — matches the pack from search.unitOfMeasures[]
  price: number; // per unit
  totalPrice: number;
  manualPriceOverride: boolean;
  searchTerm?: string;
  productUrl?: string; // Link to the actual product page
  favoriteProduct?: FavoriteProductMapping; // User's preferred product for this material
  // How this line item entered the quote: 'recommended' = generated by the
  // "Get Recommended Gear" pipeline from the job scope; 'manual' = added or
  // edited by the tradie. Captured for pipeline telemetry/review — no UI hangs
  // off it yet. Stamped once at creation and never overwritten (see withOrigin).
  origin?: 'recommended' | 'manual';
  // Pricing and product metadata
  pricingSource?: 'scraper' | 'api' | 'ai' | 'manual'; // Where the price came from
  priceConfidence?: 'high' | 'medium' | 'low'; // AI price confidence level
  // Snapshot of the row as the pricing pipeline last left it (see
  // utils/asPriced.ts). Send-time telemetry diffs the sent row against this
  // to log tradie corrections — confirmed pipeline misses. Absent on
  // hand-priced rows and quotes priced before this field shipped.
  asPriced?: {
    price: number;
    quantity: number;
    name: string;
    pricingSource?: Material['pricingSource'];
    priceConfidence?: Material['priceConfidence'];
  };
  imageUrl?: string; // Product image URL
  description?: string; // Product description
  brand?: string; // Product brand
  stockLevel?: string; // Stock availability (deprecated, use stockCheckedAt)
  stockCheckedAt?: string; // ISO timestamp of when stock was last checked
  // Material categorization
  category?: string; // Trade category ID (e.g., 'carpentry', 'electrical', 'plumbing')
  section?: string; // Work section within a job (e.g., 'Concreting', 'Timber Framing')
  templateBaseQuantity?: number; // Per-unit qty from template/AI (e.g. 2 posts per bay). quantity = templateBaseQuantity * section.multiplier
  // Detected quality tier from the job description (e.g. "high quality",
  // "premium fittings", "budget reno"). Used by candidateRanker to pick
  // the right price band out of the supplier search results instead of
  // always taking the first/cheapest hit. Inherited from the job-level
  // qualityTier on the Quote when not set per-material.
  qualityTier?: 'budget' | 'standard' | 'premium';
  // How this material's quantity relates to floorplan geometry, when the
  // quantity was grounded on an attached plan. Lets the backend deterministically
  // re-scale the quantity if the takeoff is anchored to a stated dimension.
  planBasis?: 'area' | 'perimeter' | 'volume' | 'fixed';
  // Set true when scaleMaterialsToAnchor adjusted this quantity to a stated anchor.
  quantityScaledToAnchor?: boolean;
}

// Snapshot of a Reece order placed from QuoteMate against the user's trade
// account. Stored as a sub-array on the originating quote so the user can see
// "I ordered these parts on this date" history. Reece bills the user directly
// — QuoteMate never touches money or fulfilment.
export interface ReeceOrder {
  reeceOrderNumber: string;       // Reece's order identifier from /order-gateway/orders
  placedAt: string;               // ISO timestamp
  itemCount: number;
  totalIncGst: number;
  totalExGst: number;
  cartageFee: number;
  fulfilmentMode: 'PICKUP' | 'DELIVERY';
  branchNumber?: string;          // for PICKUP
  branchName?: string;
  deliveryAddress?: string;       // for DELIVERY, single-line summary
  reference?: string;             // PO / job reference echoed to Reece
}

export interface FavoriteProductMapping {
  productName: string;
  store: string;
  productUrl?: string;
  itemNumber?: string;
  dimensions?: string;
  unit?: Material['unit'];
  price?: number; // Last known price
  imageUrl?: string; // Product image
  // Personal supplier rate fields
  isPersonalRate?: boolean;       // true → prefer over retail in auto-generate
  coveragePerUnit?: number;       // 1 unit covers N of coverageUnit (e.g. 13 m² per sheet)
  coverageUnit?: 'm²' | 'm³' | 'm';
  keywords?: string[];            // ["concrete","slab","footing"] for LLM matching
  notes?: string;
  // Provenance — PR1: 'manual', PR2: 'imported', PR3: 'subscribed'
  source?: 'manual' | 'imported' | 'subscribed';
  sourceRef?: string;             // PR2: importBatchId | PR3: supplierListId
  lastUpdatedAt?: string;         // ISO timestamp
}

export interface QuotePhoto {
  id: string;
  storageUrl: string;    // Firebase Storage download URL
  thumbnailUrl?: string;  // Optional smaller version
  annotated?: boolean;    // Whether photo has been annotated
  // Marked by the user as a plan/drawing → uploaded at higher resolution so the
  // gear generator can read its scale and dimensions.
  isPlan?: boolean;
}

// A single measurable region read off a plan. Deliberately trade-agnostic —
// "zone" (not "finish code") so the same shape serves flooring, tiling,
// painting, concreting, landscaping, etc. `code` carries a plan label when one
// is printed (FC01, R1, Room 3…) but is never required.
export interface FloorplanZone {
  label: string;          // human label, e.g. "Master bedroom" or "FC01 area"
  code?: string;          // plan-printed code if any (FC01, R1, …)
  areaM2?: number;
  // Zone boundary length and the total width of doorways/openings in it.
  // Net edge (perimeterM - openingsDeductionM) drives skirting/coving/edging
  // lineal metres for zones where the finish needs edge treatment.
  perimeterM?: number;
  openingsDeductionM?: number;
  removalAreaM2?: number; // strip-out / demolition scope for this zone
  dims?: { lengthM: number; widthM: number };
}

// Structured geometry extracted from an architectural plan/drawing in the photo
// pipeline. Always carries `assumptions` + `confidence` so a misread surfaces to
// the user instead of being silently baked into quantities.
export interface FloorplanAnalysis {
  detected: boolean;
  scale?: string;                 // "1:100"
  calibration?: {
    source: 'scale_bar' | 'known_dimension' | 'stated_total';
    basisMm?: number;             // the reference length used to set scale
    statedLengthMm?: number;      // tradie-stated overall length, echoed for the anchor
    note: string;
  };
  // Outer bounding-box dimensions the model measured for the whole plan.
  footprintDims?: { lengthM: number; widthM: number };
  totalAreaM2?: number;
  perimeterM?: number;            // drives skirting / edging / cornice / kerb
  zones?: FloorplanZone[];
  removalAreaM2?: number;         // strip-out / demolition scope
  removalBinM3?: number;          // estimated waste skip volume
  // Whether the takeoff was rescaled onto a user-stated/known real-world
  // dimension, and the linear factor applied.
  scaledToAnchor?: boolean;
  scaleFactorApplied?: number;
  // 'model' = measured/derived, 'user' = manually corrected.
  source?: 'model' | 'user';
  // User-edited overrides — when present these win over the measured values.
  // Model fields are never overwritten, so re-analysis can't wipe a correction
  // and the card can show "measured → corrected".
  corrected?: {
    totalAreaM2?: number;
    perimeterM?: number;
    removalBinM3?: number;
    // Area factor applied to the model's zone areas when the user accepted
    // "scale the other areas to match" after correcting the total. Zones stay
    // stored as measured; this scales them at read time (lengths by its √).
    zonesScaledBy?: number;
    editedAt?: string;
  };
  assumptions: string;            // what was inferred or could not be read
  confidence: 'low' | 'medium' | 'high';
}

// Labor unit type for hours/days billing
export type LaborUnit = 'hours' | 'days';

// Section within a quote/invoice with its own labor
export interface QuoteSection {
  id: string;
  name: string;               // e.g. "Colorbond Fence Bay", "Pedestrian Gate"
  multiplier: number;          // How many units (e.g. 8 bays) — default 1
  sourceTemplateId?: string;   // Which template this came from (if any)
  laborHours: number;          // Per-unit labor hours/days
  // Total labor hours/days for the section (laborHours × multiplier).
  // Persisted so consumers that don't know about multipliers (admin
  // dashboard, third-party integrations) can render the right number
  // without any math. The mobile app reads this for display; pricing
  // still derives from laborHours × multiplier × laborRate to match how
  // the editor adjusts per-unit values.
  laborHoursTotal?: number;
  laborRate: number;           // $/hour or $/day
  laborUnit: LaborUnit;        // 'hours' | 'days'
  laborTotal: number;          // calculated: laborHours * laborRate * multiplier
  sortOrder: number;
}

// Reusable section template (assembly)
export interface SectionTemplate {
  id: string;
  name: string;                // e.g. "Standard Fence Bay"
  description?: string;
  keywords?: string[];         // e.g. ["fence bay", "colorbond fence"] — for matching to job descriptions
  materials: Omit<Material, 'id'>[];  // Template materials (IDs generated on use)
  laborHours: number;
  laborRate: number;
  laborUnit: LaborUnit;
  createdAt: string;
  updatedAt: string;
}

// AI-generated template suggestion for a quote
export interface TemplateSuggestion {
  templateId: string;
  templateName: string;
  suggestedQuantity: number;
  suggestedSectionName?: string; // AI-generated contextual name (e.g. "Colorbond Fence Bay")
  reasoning: string;
}

// User-defined supplier group for materials search
export interface SupplierGroup {
  id: string;
  name: string;              // e.g. "Local Timber Yard", "Fencing Supplies Co"
  searchUrl?: string;        // Optional base URL for web scraping
  isDefault?: boolean;       // Built-in groups (Bunnings, Reece) can't be deleted
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
  // Optional contact details — surfaced in the supplier book card
  contactPerson?: string;    // Account manager / rep name
  phone?: string;
  email?: string;
  address?: string;
  notes?: string;
}

export interface SupplierPartner {
  id: string;
  name: string;
  contactPerson?: string;
  phone?: string;
  email?: string;
  address?: string;
  website?: string;
  logoUrl?: string;
  location?: { lat: number; lng: number };
  status: 'pending' | 'active' | 'suspended';
  itemCount: number;
  subscriberCount: number;
}

// Embedded job descriptor that lives inside a Quote/Invoice/Document. Pre-dates
// the top-level Job entity introduced in Phase 8 — renamed to JobSpec to free
// the name for the new top-level Job re-exported below.
export interface JobSpec {
  id: string;
  name: string;
  description: string;
  template?: 'stairs' | 'deck' | 'fence' | 'pergola' | 'custom';
  estimatedHours?: number;
  customParams?: Record<string, number>; // e.g., { steps: 15, length: 10 }
  // Geometry read off an attached plan during gear generation (area, perimeter,
  // per-zone breakdown). Present only when a floorplan/drawing was detected.
  floorplanAnalysis?: FloorplanAnalysis;
}

// Top-level Job entity. Re-exported from the shared module so the app and
// the backend agree on the shape.
export type { Job, JobStage, JobPhoto } from '../../shared/job/types';

export interface Quote {
  id: string;
  quoteNumber?: string; // Human-readable reference number (e.g., "Q-001")
  createdAt: Date;
  updatedAt: Date;
  contactId?: string; // Link to Contact for live updates
  customerName: string;
  customerEmail?: string;
  customerPhone?: string;
  jobAddress?: string;
  job: JobSpec;
  materials: Material[];
  laborRate: number; // $/hour or $/day (depending on laborUnit)
  laborHours: number; // quantity of hours or days
  laborUnit?: LaborUnit; // 'hours' | 'days' — default 'hours' for backwards compat
  laborTotal: number;
  // Extra labour hours added on top of (or subtracted from) the section sums.
  // Lets the user nudge total labour without rebalancing per-section values.
  // Can be negative. Falls back to 0 for legacy quotes.
  laborExtraHours?: number;
  materialsSubtotal: number;
  markup: number; // material markup percentage
  laborMarkup?: number; // labor markup percentage (independent from material markup). Falls back to material markup for legacy quotes.
  markupAmount: number; // combined material + labor markup amount
  subtotal: number;
  gst: number;
  total: number;
  // Sections — optional, for quotes with multiple work sections
  sections?: QuoteSection[];
  status: 'draft' | 'sent' | 'accepted' | 'rejected' | 'completed' | 'cancelled';
  // First-send audit. Set once when the quote first leaves draft via any
  // delivery path (email/sms/share/export). Never overwritten on re-send.
  sentAt?: number; // epoch-ms
  sendMethod?: SendMethod; // channel used for the first send
  draftStep?: string; // Screen name where user left off during quote flow (e.g., 'CustomerDetails')
  notes?: string;
  // Job-level quality tier inferred from the description ("premium",
  // "high quality", "budget", etc.). Inherited by materials that don't
  // carry their own qualityTier — see candidateRanker.pickBestCandidate.
  qualityTier?: 'budget' | 'standard' | 'premium';
  aiSkipped?: boolean; // Flag to indicate AI analysis was intentionally skipped
  // AI template suggestions (generated during description cleanup or on materials screen load)
  templateSuggestions?: TemplateSuggestion[];
  // Markup visibility
  showMarkup?: boolean;        // Show markup line on customer-facing documents. Default: false (hidden)
  // Materials cost visibility on PDFs/email. When false, both the materials
  // table and the Materials Subtotal summary row are hidden. Undefined =
  // inherit BusinessSettings.showMaterialCostsByDefault.
  showMaterialCosts?: boolean;
  // Labour cost visibility on PDFs/email. When false, both the labour table
  // and the Labour summary row are hidden. Undefined = inherit
  // BusinessSettings.showLaborCostsByDefault.
  showLaborCosts?: boolean;
  // Labour breakdown visibility on PDFs. When false, the per-section labour
  // rows are hidden and only the Labour Total is shown. Default: true.
  showLaborBreakdown?: boolean;
  // Travel adjustment
  travelAdjustment?: number;   // percentage bump (e.g., 3 = +3%)
  estimatedDistance?: number;   // km (straight-line)
  estimatedFuelCost?: number;  // AUD (round trip)
  travelGeocodeFailed?: boolean; // true when address geocoding couldn't resolve
  // Quote acceptance via email link fields
  acceptanceToken?: string; // 64-char secure token for email acceptance link
  acceptanceTokenCreatedAt?: Date; // When the token was generated (for 30-day expiration)
  respondedAt?: Date; // When client accepted/rejected via email link
  respondedBy?: string; // Client identifier (email or name from form)
  clientNotes?: string; // Optional feedback from client when responding
  // Job photos
  photos?: QuotePhoto[];
  // AI email content (stored at send time for acceptance page)
  aiEmailBody?: string;
  // In-progress email body shown in the email preview modal. Generated (or
  // typed) on first open and persisted so reopening the modal doesn't trigger
  // a fresh AI generation. The Regenerate button overwrites this. Distinct
  // from aiEmailBody, which is the canonical record of what was sent.
  draftEmailBody?: string;
  draftEmailSubject?: string;

  // Deposit / pre-payment (paid against the quote before work starts).
  // requireDeposit is the authoritative toggle — when false, no deposit is
  // asked for regardless of depositPercentage (which we preserve so toggling
  // back on restores the previous value).
  // depositAmount is the dollar amount snapshotted at quote-send time so it
  // doesn't drift if totals are edited after sending.
  requireDeposit?: boolean;
  depositPercentage?: number;
  depositAmount?: number;
  depositPaid?: number;            // Dollars actually received (set by Square webhook).
  depositPaidAt?: Date;
  depositPaymentLinkId?: string;   // Square payment link id minted on quote send.
  depositPaymentLinkUrl?: string;  // Hosted checkout URL surfaced on the acceptance page.
  depositPaymentLinkCreatedAt?: number | Date; // When the link was minted (ms epoch). Used to detect >23h stale and re-mint.
  depositSquarePaymentId?: string; // Set by webhook on COMPLETED (idempotency key).

  // GST mode snapshotted at quote creation. When true, line prices are
  // GST-inclusive and the GST line shows the extracted 1/11. When false,
  // prices are ex-GST and 10% is added on top. Falls back to the business
  // setting when undefined (legacy quotes).
  pricesIncludeGst?: boolean;
  // Whether the business was GST-registered when the quote was created.
  // undefined/true = registered; false = not registered (no GST calculated
  // or shown, document carries a "No GST has been charged" note).
  gstRegistered?: boolean;

  // T&Cs snapshot taken at send-time so later edits to the BusinessProfile
  // T&Cs don't rewrite history. The hash identifies the exact version the
  // customer saw when they paid.
  termsSnapshot?: string;
  termsVersionHash?: string;
  // Stamped by the Square webhook when the deposit/full payment completes.
  // Legally: the customer received the PDF containing the terms (hash match)
  // and completing payment = accepting those terms.
  depositTcAccepted?: TcAcceptance;
  fullTcAccepted?: TcAcceptance;

  // Forward-compat: once we introduce a Jobs collection, accepted quotes with
  // a paid deposit auto-create a Job linked here. Pre-wiring now so existing
  // quotes gain the field without a migration later.
  jobId?: string;
  // Computed server-side by the webhook: total money received against this
  // quote (deposit + any extra payments) and the outstanding balance.
  // Redundant with depositPaid for now, but collapses to a single "how much
  // has this customer paid" field once multi-payment lands.
  paidTotal?: number;
  balanceDue?: number;

  // Non-null when the last Square webhook attempt against this quote failed
  // to reconcile — surfaced as a red banner so the tradie can investigate
  // instead of silently losing the payment event. Cleared on next success.
  paymentSyncError?: PaymentSyncError;

  // Chargeback / dispute state as reported by Square. Null unless a dispute
  // has been opened against a payment linked to this quote.
  disputeStatus?: SquareDisputeStatus;
  disputeId?: string;

  // Set when this quote has been converted to an invoice. Used for idempotency
  // — re-tapping Convert returns the existing invoice instead of duplicating.
  invoiceId?: string;
  invoicedAt?: Date;

  // Reece orders placed against this quote's materials. Each entry is a
  // confirmed order — Reece bills the user via their trade account, QuoteMate
  // never touches the money. Append-only history; cancelling an order is done
  // through Reece's website, not QuoteMate.
  reeceOrders?: ReeceOrder[];

  // Xero integration — populated when the quote is pushed to Xero as a Quote
  // (status DRAFT / SENT / ACCEPTED / DECLINED). Contact id is shared with
  // the invoice generated from this quote so we don't create duplicate
  // contacts in Xero.
  xeroQuoteId?: string;
  xeroContactId?: string;
  xeroSyncStatus?: XeroSyncStatus;
  xeroSyncedAt?: Date;
  xeroSyncError?: string;
}

export type SquareDisputeStatus =
  | 'INQUIRY_EVIDENCE_REQUIRED'
  | 'INQUIRY_PROCESSING'
  | 'INQUIRY_CLOSED'
  | 'EVIDENCE_REQUIRED'
  | 'PROCESSING'
  | 'WON'
  | 'LOST'
  | 'ACCEPTED';

// Recorded when the Square webhook fails mid-reconcile. Surfaces in-app so
// the tradie knows something needs manual attention (instead of us swallowing
// the error silently, which is the default for webhook handlers).
export interface PaymentSyncError {
  at: Date;
  // Short machine-readable identifier — e.g. 'index_lookup_failed',
  // 'firestore_write_failed', 'xero_sync_failed'. Used for conditional UI.
  code: string;
  message: string;        // One-line human explanation for the banner.
  paymentId?: string;     // Square payment id if known.
}

export interface JobTemplate {
  id: string;
  name: string;
  description: string;
  icon?: string;
  defaultMaterials: TemplateMaterial[];
  estimatedHoursFormula: string; // e.g., "steps * 0.5"
  requiredParams: TemplateParam[]; // e.g., [{ key: 'steps', label: 'Number of steps', unit: '' }]
  // Trade-specific copy that shapes the job description input.
  // questionsLine: short prompt of the variables that matter for this job type.
  // exampleLines: a filled-in example using this trade's vocabulary.
  // voicePromptHint: short sub-label under the record button.
  questionsLine?: string;
  exampleLines?: string;
  voicePromptHint?: string;
}

export interface TemplateMaterial {
  name: string;
  searchTerm: string; // what to search in Bunnings
  quantityFormula: string; // e.g., "steps * 2"
  unit: 'each' | 'm' | 'm²' | 'm³' | 'L' | 'kg' | 'box' | 'pack';
}

export interface TemplateParam {
  key: string;
  label: string;
  unit?: string;
  defaultValue?: number;
}

export type TradeType = 'all' | 'carpenter' | 'cabinet_maker' | 'plumber' | 'electrician' | 'cleaner';

export interface HardwareStore {
  name: string;
  url: string;
  description: string;
}

// Payment method types for business settings
export type PaymentMethodType = 'bank_transfer' | 'paypal' | 'bpay' | 'payid' | 'other';

export interface BankAccountDetails {
  enabled?: boolean;
  accountName?: string;
  bsb?: string;
  accountNumber?: string;
}

export interface BPayDetails {
  enabled?: boolean;
  billerCode?: string;
  referenceNumber?: string;
}

export interface PayIDDetails {
  enabled?: boolean;
  payIdType?: 'phone' | 'email' | 'abn';
  payIdValue?: string;
}

export interface PayPalDetails {
  enabled?: boolean;
  email?: string;
}

export interface OtherPaymentDetails {
  enabled?: boolean;
  instructions?: string;
}

export interface PaymentMethodSettings {
  // Master toggle - show payment section on PDFs
  showOnDocuments: boolean;
  // Individual payment methods
  bankAccount?: BankAccountDetails;
  paypal?: PayPalDetails;
  bpay?: BPayDetails;
  payId?: PayIDDetails;
  other?: OtherPaymentDetails;
}

/**
 * A licence or accreditation shown on customer-facing documents. The badge
 * carries the same variant fields as the company logo so both go through the
 * one editor — see components/BrandImageEditor.
 */
export interface BusinessCredential {
  id: string;
  /** Customer-facing name, e.g. "ARC Authorisation" or "Electrical licence". */
  label: string;
  /** Licence / authorisation number shown beside the name, e.g. "AU12345". */
  number?: string;
  /** Optional accreditation badge supplied by the business. */
  logoUri?: string;
  /** Both processed variants, so the choice below stays reversible. */
  logoOriginalUri?: string;
  logoNoBackgroundUri?: string;
  logoBackground?: 'transparent' | 'light' | 'dark' | 'busy';
  logoUseNoBackground?: boolean;
}

export interface BusinessSettings {
  businessName: string;
  abn?: string;
  email?: string;
  phone?: string;
  address?: string;
  website?: string; // Shown on PDFs/emails alongside other contact details
  logoUri?: string; // The logo the PDFs actually use — whichever variant is chosen
  // Both variants the server produced from the upload, so the choice below can
  // be flipped later without re-uploading. See functions/src/logoProcessing.ts.
  logoOriginalUri?: string;
  logoNoBackgroundUri?: string; // absent when removing the background is unsafe
  logoBackground?: 'transparent' | 'light' | 'dark' | 'busy';
  // The tradie's pick. Undefined means "follow the recommendation".
  logoUseNoBackground?: boolean;
  // Repeatable licences/accreditations rendered as one compact banner on
  // quote, invoice and service-report PDFs.
  credentials?: BusinessCredential[];
  defaultLaborRate: number;
  defaultMarkup: number;
  defaultLaborMarkup?: number; // Default labor markup percentage. Falls back to defaultMarkup if undefined.
  transportMarkupEnabled?: boolean; // Whether to include transport/logistics markup on quotes (default: true)
  // Trade type
  tradeType?: TradeType; // Default: 'all'
  // New: Trade category and niche for improved targeting (multi-select)
  tradeCategories?: string[]; // e.g., ['plumbing', 'carpentry']
  tradeNiches?: string[]; // e.g., ['drain_services', 'outdoor']
  // Legacy single-select fields (kept for backwards compatibility)
  tradeCategory?: string;
  tradeNiche?: string;
  // Price fetching settings
  useReeceApi?: boolean; // If true and tradeType is plumber, use Reece API for plumbing supplies
  selectedStore?: string; // DEPRECATED — kept for legacy reads. Hardware store routing now uses supplierPriority.
  // User-controlled supplier priority for material price lookups. Higher in
  // the list = tried first. Entries are either built-in identifiers
  // ('bunnings', 'reece') or a SupplierGroup.id from the user's saved local
  // suppliers. Bunnings is the always-on backbone — if it's missing from
  // this list, treat it as appended at the end. Reece is only honoured
  // when the user has connected (the integration screen flips that on).
  supplierPriority?: string[];
  // Auto-nudge customers who haven't accepted a sent quote. Off by default.
  // When on, the customerQuoteFollowUp scheduled function emails the
  // customer ~3 days after send and again ~7 days, capped at 2 nudges.
  autoCustomerFollowUpEnabled?: boolean;
  // When on (the default — undefined counts as on), Mate auto-starts the
  // mic on tab focus if mic permission is already granted, so voice mode is
  // immediately live without a tap. Set false to opt out.
  autoStartMicOnMate?: boolean;
  // Quote display settings
  showLaborHours?: boolean; // If true, show labor hours breakdown on quotes. Default: false (show only total)
  showMarkup?: boolean; // If true, allow per-document markup line. When undefined or false, markup is hidden across all documents. Default: false (hide markup).
  // Default for new quotes' showMaterialCosts. When false, new quotes hide
  // the materials table + Materials Subtotal row by default. Per-quote
  // toggle on Quote.showMaterialCosts overrides. Default: true.
  showMaterialCostsByDefault?: boolean;
  // Default for new quotes' showLaborCosts. Same shape as above for labour.
  showLaborCostsByDefault?: boolean;
  // Payment method settings
  paymentMethods?: PaymentMethodSettings;
  // Branding
  brandColor?: string; // Custom accent color for PDF documents (overrides template default)
  // Quote/invoice display settings
  groupMaterialsBySection?: boolean; // Group materials by work section on PDFs (default: false)
  // PDF template
  pdfTemplate?: PdfTemplateId;
  // Whether new quotes should require a deposit by default. Separate from the
  // amount so disabling doesn't wipe the percentage. Per-quote override on
  // Quote.requireDeposit.
  requireDepositByDefault?: boolean;
  // Default deposit percentage applied to new quotes when requireDeposit is on.
  // Per-quote override lives on Quote.depositPercentage.
  defaultDepositPercentage?: number;
  // GST handling: when true, prices entered/displayed are GST-inclusive and
  // the GST line on quotes/invoices shows the extracted 1/11 component for
  // tax-invoice disclosure. When false (default for new users), prices are
  // ex-GST and 10% GST is added on top. Snapshotted onto each Quote/Invoice
  // at creation time so toggling the setting later doesn't rewrite history.
  pricesIncludeGst?: boolean;
  // Whether the business is registered for GST. undefined/true = registered
  // (pricesIncludeGst decides inclusive vs exclusive); false = not registered:
  // no GST is calculated or shown anywhere, and documents carry a "No GST has
  // been charged" note. Snapshotted onto each Quote/Invoice like
  // pricesIncludeGst.
  gstRegistered?: boolean;
  // Terms & Conditions shown on the quote/invoice PDF and recorded as
  // accepted when the customer pays. Editable in Settings → Business Profile.
  // When blank, the PDF falls back to the built-in AU tradie default so new
  // users have something sensible out of the box.
  termsAndConditions?: string;
  // ISO timestamp of the last edit; used to prompt re-review if the business
  // hasn't touched their terms in >12 months.
  termsUpdatedAt?: string;
  // When true, bump the Square pay-link amount by the standard passthrough
  // percentage (see shared/pdf/squareFees.ts → PASSTHROUGH_SURCHARGE_PCT) so
  // the customer covers both Square's processing fee and QuoteMate's platform
  // fee rather than the tradie eating them. Legal in AU with disclosure; the
  // email + hosted checkout surface the surcharge line. Default false.
  // The percentage is NOT tradie-editable — ACCC rules require surcharges to
  // stay at or under the actual cost of acceptance.
  surchargePaymentFees?: boolean;
  // Legacy fields (kept for backwards compatibility)
  hardwareStores?: string[]; // DEPRECATED - use selectedStore instead
  customStores?: string[]; // DEPRECATED - Custom store URLs added by user
}

// Quote calculation result
export interface QuoteCalculation {
  materialsSubtotal: number;
  laborTotal: number;
  subtotal: number;
  markupAmount: number;
  travelAdjustmentAmount: number;
  gst: number;
  total: number;
}

// Subscription
//
// Tier model:
//   trial — 14 days of full Pro behaviour, no Square required.
//   free  — unlimited use, but Square mandatory; only Square offered as a
//           payment method; every delivered quote/invoice carries a Square
//           pay link. Platform takes platformFeeBps (default 170 = 1.7%).
//   pro   — paid; full payment-method choice, no delivery gating.
//           Platform takes platformFeeBps (default 100 = 1%).
//
// `isPro` is kept for backwards compatibility and is treated as a derived
// boolean equivalent to plan === 'pro'. The SubscriptionPlan type is defined
// alongside the affiliate types further down — extended there to include
// 'trial' so the on-ramp tier is part of the same union.
export interface SubscriptionStatus {
  isPro: boolean;
  plan?: SubscriptionPlan;
  quotesThisMonth: number;
  currentPeriodStart: Date;
  currentPeriodEnd: Date;
  freeQuotesLimit: number;
  trialStartedAt?: Date;
  trialExpired?: boolean;
  dismissedUpgradeBanner?: boolean;
  platformFeeBps?: number;
}

export interface ReferralInfo {
  referralCode: string;
  referredBy: string | null;
  totalReferrals: number;
  convertedReferrals: number;
  // Affiliate fields
  isAffiliate: boolean;
  commissionRate: number; // e.g. 0.50 for 50%
  totalEarnings: number; // lifetime earnings in cents
  pendingEarnings: number; // awaiting payout in cents
  paidEarnings: number; // already paid out in cents
  lastPayoutAt: Date | null;
}

export interface AffiliateEarning {
  id: string;
  referredUserId: string;
  referredUserEmail: string; // masked, e.g. "j***@gmail.com"
  platform: 'web' | 'ios' | 'android';
  grossAmount: number; // cents
  platformFee: number; // cents
  netRevenue: number; // cents
  commissionRate: number;
  commissionAmount: number; // cents
  billingPeriod: string; // e.g. "2026-03"
  productId: string;
  status: 'pending' | 'confirmed' | 'paid' | 'cancelled';
  createdAt: Date;
}

export type SubscriptionPlan = 'trial' | 'free' | 'pro';

// Invoice types
export type PaymentTerms = 'due_on_receipt' | 'net_7' | 'net_14' | 'net_30' | 'custom';
export type InvoiceStatus = 'draft' | 'sent' | 'paid' | 'partial' | 'overdue' | 'cancelled';
export type PaymentMethod = 'cash' | 'bank_transfer' | 'card' | 'cheque' | 'other';

export interface Invoice {
  id: string;
  invoiceNumber?: string;
  createdAt: Date;
  updatedAt: Date;
  issueDate: Date;
  dueDate: Date;

  // Customer (same as Quote)
  contactId?: string; // Link to Contact for live updates
  customerName: string;
  customerEmail?: string;
  customerPhone?: string;
  jobAddress?: string;

  // Job & Materials (same as Quote)
  job: JobSpec;
  materials: Material[];

  // Pricing (same as Quote)
  laborRate: number;
  laborHours: number;
  laborUnit?: LaborUnit;
  laborTotal: number;
  // Extra labour hours added on top of (or subtracted from) the section sums.
  // Mirrors Quote.laborExtraHours. Falls back to 0 for legacy invoices.
  laborExtraHours?: number;
  materialsSubtotal: number;
  markup: number; // material markup percentage
  laborMarkup?: number; // labor markup percentage (independent from material markup). Falls back to material markup for legacy invoices.
  markupAmount: number; // combined material + labor markup amount
  subtotal: number;
  gst: number;
  total: number;

  // Sections — optional, for invoices with multiple work sections
  sections?: QuoteSection[];

  // Markup visibility
  showMarkup?: boolean;        // Show markup line on customer-facing documents. Default: false (hidden)
  // Materials cost visibility on PDFs/email. When false, both the materials
  // table and the Materials Subtotal summary row are hidden. Undefined =
  // inherit BusinessSettings.showMaterialCostsByDefault.
  showMaterialCosts?: boolean;
  // Labour cost visibility on PDFs/email. When false, both the labour table
  // and the Labour summary row are hidden. Undefined = inherit
  // BusinessSettings.showLaborCostsByDefault.
  showLaborCosts?: boolean;
  // Labour breakdown visibility on PDFs. When false, the per-section labour
  // rows are hidden and only the Labour Total is shown. Default: true.
  showLaborBreakdown?: boolean;

  // Invoice-specific
  status: InvoiceStatus;
  // First-send audit. Set once when the invoice first leaves draft via any
  // delivery path (email/sms/share/export). Never overwritten on re-send.
  sentAt?: number; // epoch-ms
  sendMethod?: SendMethod; // channel used for the first send
  paymentTerms: PaymentTerms;
  customPaymentDays?: number;

  // Payment tracking
  paidDate?: Date;
  paidAmount?: number;
  paymentMethod?: PaymentMethod;
  paymentNotes?: string;

  // Link to source quote
  sourceQuoteId?: string;

  notes?: string;

  // Travel adjustment
  travelAdjustment?: number;   // percentage bump (e.g., 3 = +3%)
  estimatedDistance?: number;   // km (straight-line)
  estimatedFuelCost?: number;  // AUD (round trip)
  travelGeocodeFailed?: boolean; // true when address geocoding couldn't resolve

  // Xero integration
  xeroInvoiceId?: string;      // Xero invoice ID (for idempotent updates)
  xeroContactId?: string;      // Xero contact ID
  xeroSyncStatus?: XeroSyncStatus;
  xeroSyncedAt?: Date;         // Last successful sync timestamp
  xeroSyncError?: string;      // Last sync error message

  // Square online payment
  squarePaymentLinkId?: string;   // Square Checkout API payment link id
  squarePaymentLinkUrl?: string;  // Hosted checkout URL included in the invoice email
  squarePaymentId?: string;       // Set by webhook when a payment is COMPLETED (idempotency key)
  squarePaidAt?: Date;            // When the Square webhook reported payment completion

  // Deposit credit carried over from the source quote.
  // depositCredit reduces the amount owing; the line is rendered as
  // "Deposit of $X already paid" on the invoice/PDF/email.
  depositCredit?: number;
  depositCreditFromQuoteId?: string;

  // GST mode snapshotted at invoice creation. See Quote.pricesIncludeGst.
  pricesIncludeGst?: boolean;
  // GST registration snapshotted at invoice creation. See Quote.gstRegistered.
  gstRegistered?: boolean;

  // T&Cs snapshot taken at send-time — see Quote.termsSnapshot.
  termsSnapshot?: string;
  termsVersionHash?: string;
  // Stamped by the Square webhook when the invoice payment completes.
  tcAccepted?: TcAcceptance;

  // Forward-compat job linkage — mirrors Quote.jobId.
  jobId?: string;
  // Total dollars received against this invoice. paidAmount is the legacy
  // single-payment field we keep in sync.
  paidTotal?: number;
  balanceDue?: number;

  // Failed-webhook surface + dispute tracking, mirrors Quote.
  paymentSyncError?: PaymentSyncError;
  disputeStatus?: SquareDisputeStatus;
  disputeId?: string;

  // In-progress email body shown in the invoice email preview modal.
  // Generated (or typed) on first open and persisted so reopening doesn't
  // trigger a fresh AI generation. Regenerate overwrites it.
  draftEmailBody?: string;
  draftEmailSubject?: string;
}

// Xero integration types
export type XeroSyncStatus = 'not_synced' | 'syncing' | 'synced' | 'error';

export interface XeroConnection {
  tenantId: string;            // Xero organisation ID
  tenantName: string;          // Xero organisation name
  connectedAt: string;         // ISO date
  lastSyncAt?: string;         // ISO date
  syncEnabled: boolean;        // Auto-push on invoice send
}

// Square integration types
export type SquareEnv = 'sandbox' | 'production';

export interface SquareConnection {
  merchantId: string;
  merchantName?: string;       // Best-effort display name from Square merchant profile
  locationId?: string;         // Default location used for payment links
  locationName?: string;
  env: SquareEnv;
  connectedAt: string;         // ISO date
  // Access/refresh tokens live server-side only — this type is mirrored by
  // Firestore at users/{uid}/settings/squareConnection, but the mobile app
  // only ever reads the non-sensitive subset via checkSquareConnection().
  disconnectedReason?: string | null;
}

// Contact types
export type ContactSource = 'manual' | 'phone' | 'xero' | 'quote';

export interface Contact {
  id: string;
  name: string;
  businessName?: string;
  email?: string;
  phone?: string;
  address?: string;
  website?: string;
  source: ContactSource;
  xeroContactId?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface SearchableContact extends Contact {
  searchSource: 'saved' | 'phone' | 'recent' | 'xero';
}

// Notification preferences (stored at users/{userId}/settings/notificationPreferences)
export interface NotificationPreferences {
  quoteUpdates: boolean;       // Quote accepted/rejected/viewed/expiring
  invoiceUpdates: boolean;     // Invoice paid/overdue
  dailyMotivation: boolean;    // Morning Aussie motivation
  milestoneCelebrations: boolean; // Quote count milestones
  inactivityNudges: boolean;   // "We miss ya" nudges
}
