import { StyleSheet } from 'react-native';
import { makeStyles } from '../../../theme';

export const useAddMaterialStyles = makeStyles((t) => ({
  container: {
    flex: 1,
    backgroundColor: t.colors.bg,
  },
  tabBar: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 8,
    backgroundColor: t.colors.surfaceRaised,
    borderBottomWidth: 1,
    borderBottomColor: t.colors.border,
  },
  tabContent: {
    flex: 1,
  },
  syncedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: t.colors.accentSubtle,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    marginLeft: 6,
  },
  syncedBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: t.colors.accentText,
  },
  discoverCard: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
    marginBottom: 4,
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: t.colors.surfaceRaised,
    borderRadius: 10,
  },
  discoverCardText: {
    flex: 1,
    fontSize: 14,
    color: t.colors.text,
    fontWeight: '500',
  },
  importCard: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 12,
    paddingVertical: 14,
    paddingHorizontal: 14,
    backgroundColor: t.colors.accentSubtle,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: t.colors.accentSubtle,
  },
  importCardIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: t.colors.accentSubtle,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  importCardBody: {
    flex: 1,
  },
  importCardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: t.colors.textSecondary,
  },
  importCardSubtitle: {
    marginTop: 2,
    fontSize: 12,
    color: t.colors.textMuted,
  },
  importCardChevron: {
    marginLeft: 4,
  },
  addManuallyLink: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginBottom: 4,
  },
  addManuallyLinkText: {
    marginLeft: 6,
    color: t.colors.accentText,
    fontSize: 13,
    fontWeight: '600',
  },
  advancedToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    marginTop: 4,
  },
  advancedToggleText: {
    marginLeft: 4,
    color: t.colors.accentText,
    fontSize: 13,
    fontWeight: '600',
  },
  coverageHelper: {
    fontSize: 12,
    color: t.colors.textMuted,
    marginBottom: 8,
    lineHeight: 16,
  },
  linkedBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: t.colors.accentSubtle,
    borderColor: t.colors.accentSubtle,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 12,
  },
  linkedBannerText: {
    flex: 1,
    marginLeft: 8,
    fontSize: 12,
    color: t.colors.text,
    fontWeight: '500',
  },
  // Pill toggle — same shape as the Hours/Days control on the labor screen.
  pillToggleRow: {
    flexDirection: 'row',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: t.colors.border,
    overflow: 'hidden',
  },
  pillToggleBtn: {
    flex: 1,
    flexDirection: 'row',
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: t.colors.surfaceRaised,
  },
  pillToggleIcon: {
    marginRight: 6,
  },
  pillToggleBtnActive: {
    backgroundColor: t.colors.accent,
  },
  pillToggleText: {
    fontSize: 14,
    fontWeight: '600',
    color: t.colors.textMuted,
  },
  pillToggleTextActive: {
    color: t.colors.onAccent,
  },
  // Supplier section header — modeled on the materials-list section card header
  supplierHeader: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginTop: 12,
    marginBottom: 8,
    backgroundColor: t.colors.surfaceRaised,
    borderRadius: 12,
  },
  supplierHeaderTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  supplierHeaderContactRow: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: t.colors.border,
  },
  supplierHeaderChevron: {
    width: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  supplierHeaderNameWrap: {
    flex: 1,
    paddingHorizontal: 4,
  },
  supplierHeaderName: {
    fontSize: 15,
    fontWeight: '700',
    color: t.colors.text,
  },
  supplierHeaderCount: {
    fontSize: 11,
    color: t.colors.textMuted,
    marginTop: 2,
  },
  supplierHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  supplierHeaderActionBtn: {
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  savedItemSeparator: {
    height: 0,
  },
  scrollContent: {
    paddingBottom: 140,
  },
  section: {
    padding: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 8,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: t.colors.text,
    marginBottom: 12,
  },
  manualEntryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    gap: 12,
  },
  manualEntryDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: t.colors.border,
  },
  manualEntryHeaderText: {
    fontSize: 13,
    fontWeight: '500',
    color: t.colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  searchTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  proSearchPrompt: {
    backgroundColor: t.colors.surfaceRaised,
    borderWidth: 1,
    borderColor: t.colors.border,
    borderRadius: 8,
    padding: 16,
    alignItems: 'center',
    gap: 8,
  },
  proSearchPromptText: {
    fontSize: 14,
    color: t.colors.textSecondary,
    textAlign: 'center',
  },
  proSearchPromptCta: {
    fontSize: 14,
    fontWeight: '600',
    color: t.colors.accentText,
  },
  searchInput: {
    marginBottom: 16,
  },
  searchBarContainer: {
    marginBottom: 16,
  },
  // Mirrors InlineAddMaterialRow's `nameRow` — bordered pill with the input
  // on the left and the search button tucked into the right edge.
  searchBarInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: t.colors.surfaceRaised,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: t.colors.border,
    paddingLeft: 12,
    paddingRight: 0,
    overflow: 'hidden',
  },
  searchBarInput: {
    flex: 1,
    backgroundColor: 'transparent',
    height: 48,
  },
  searchBarInputContent: {
    paddingLeft: 0,
  },
  searchBarButton: {
    width: 56,
    height: '100%',
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderTopRightRadius: 11,
    borderBottomRightRadius: 11,
  },
  searchBarButtonIdle: {
    backgroundColor: t.colors.accentSubtle,
  },
  searchBarButtonActive: {
    backgroundColor: t.colors.accent,
  },
  searchBarButtonCancel: {
    backgroundColor: t.colors.textMuted,
  },
  supplierChipsRow: {
    flexDirection: 'row',
    marginBottom: 12,
    maxHeight: 36,
  },
  supplierChip: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: t.colors.border,
    backgroundColor: t.colors.surfaceRaised,
    marginRight: 8,
  },
  supplierChipActive: {
    backgroundColor: t.colors.accent,
    borderColor: t.colors.accent,
  },
  supplierChipText: {
    fontSize: 13,
    fontWeight: '500',
    color: t.colors.textMuted,
  },
  supplierChipTextActive: {
    color: t.colors.onAccent,
  },
  loadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  loadingText: {
    marginLeft: 12,
    fontSize: 14,
    color: t.colors.textSecondary,
  },
  resultsContainer: {
    marginTop: 8,
  },
  resultsHeader: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 12,
    color: t.colors.textSecondary,
  },
  resultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
  },
  resultImage: {
    width: 60,
    height: 60,
    marginRight: 12,
    borderRadius: 8,
    backgroundColor: t.colors.surfaceOverlay,
    borderWidth: 1,
    borderColor: t.colors.border,
  },
  resultInfo: {
    flex: 1,
  },
  resultName: {
    fontSize: 15,
    fontWeight: '500',
    marginBottom: 4,
    color: t.colors.text,
  },
  resultDetails: {
    fontSize: 12,
    color: t.colors.textSecondary,
    marginBottom: 4,
  },
  resultPrice: {
    fontSize: 14,
    fontWeight: '600',
    color: t.colors.money,
    marginBottom: 4,
  },
  aiChip: {
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  aiChipText: {
    fontSize: 10,
  },
  recentChipsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  recentChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: t.colors.surfaceRaised,
    borderWidth: 1,
    borderColor: t.colors.border,
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 14,
    gap: 6,
  },
  recentChipName: {
    fontSize: 13,
    color: t.colors.text,
    maxWidth: 150,
  },
  recentChipPrice: {
    fontSize: 12,
    fontWeight: '600',
    color: t.colors.money,
  },
  divider: {
    marginVertical: 8,
  },
  input: {
    marginBottom: 12,
  },
  row: {
    flexDirection: 'row',
    gap: 12,
  },
  halfWidth: {
    flex: 1,
  },
  quantityStepperContainer: {
    marginBottom: 12,
  },
  quantityLabel: {
    fontSize: 12,
    color: t.colors.textSecondary,
    marginBottom: 6,
    marginLeft: 4,
  },
  quantityStepper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: t.colors.border,
    borderRadius: 8,
    backgroundColor: t.colors.surfaceRaised,
    height: 48,
  },
  stepperButton: {
    width: 44,
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantityInput: {
    flex: 1,
    textAlign: 'center',
    backgroundColor: 'transparent',
    height: 48,
  },
  quantityInputContent: {
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '600',
  },
  unitSelector: {
    marginBottom: 16,
  },
  unitLabel: {
    fontSize: 12,
    color: t.colors.textSecondary,
    marginBottom: 8,
    marginLeft: 4,
  },
  unitButtons: {
    gap: 8,
  },
  unitRow: {
    marginBottom: 4,
  },
  categorySelector: {
    marginBottom: 16,
  },
  categoryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: t.colors.surfaceRaised,
    borderWidth: 1,
    borderColor: t.colors.border,
    borderRadius: 8,
    padding: 12,
    gap: 8,
  },
  categoryButtonText: {
    flex: 1,
    fontSize: 14,
    color: t.colors.text,
  },
  categoryList: {
    marginTop: 8,
    backgroundColor: t.colors.surfaceRaised,
    borderWidth: 1,
    borderColor: t.colors.border,
    borderRadius: 8,
    maxHeight: 250,
    overflow: 'hidden',
  },
  categoryItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    gap: 10,
    borderBottomWidth: 1,
    borderBottomColor: t.colors.border,
  },
  categoryItemSelected: {
    backgroundColor: t.colors.accentSubtle,
  },
  categoryItemText: {
    flex: 1,
    fontSize: 14,
    color: t.colors.text,
  },
  categoryItemTextSelected: {
    color: t.colors.accentText,
    fontWeight: '600',
  },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
    paddingVertical: 8,
  },
  toggleLabel: {
    fontSize: 14,
    color: t.colors.text,
    flex: 1,
    marginRight: 12,
  },
  savedList: {
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  savedItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: t.colors.surfaceRaised,
    marginBottom: 8,
    borderRadius: 8,
    overflow: 'hidden',
    paddingVertical: 12,
    paddingHorizontal: 12,
  },
  savedIcon: {
    marginRight: 12,
  },
  savedItemImage: {
    width: 50,
    height: 50,
    marginRight: 12,
    borderRadius: 8,
    backgroundColor: t.colors.surfaceOverlay,
    borderWidth: 1,
    borderColor: t.colors.border,
  },
  savedInfo: {
    flex: 1,
  },
  savedNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  savedName: {
    fontSize: 15,
    fontWeight: '500',
    color: t.colors.text,
    flexShrink: 1,
  },
  myRateChip: {
    backgroundColor: t.colors.accent,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
  },
  myRateChipText: {
    color: t.colors.onAccent,
    fontSize: 11,
    fontWeight: '600',
  },
  personalRateFields: {
    marginTop: 4,
    marginBottom: 8,
    padding: 12,
    backgroundColor: t.colors.surfaceOverlay,
    borderRadius: 8,
    gap: 8,
  },
  personalRateHelper: {
    fontSize: 12,
    color: t.colors.textSecondary,
    marginBottom: 4,
    lineHeight: 16,
  },
  savedDetails: {
    fontSize: 12,
    color: t.colors.textSecondary,
    marginBottom: 2,
  },
  savedPrice: {
    fontSize: 13,
    fontWeight: '600',
    color: t.colors.money,
  },
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
  },
  emptyStateTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: t.colors.text,
    marginTop: 16,
    marginBottom: 8,
  },
  emptyStateText: {
    fontSize: 14,
    color: t.colors.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
  },
  cantFindItPrompt: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 12,
    marginTop: 8,
  },
  cantFindItText: {
    marginLeft: 8,
    color: t.colors.accentText,
    fontSize: 14,
    fontWeight: '600',
  },
  // Horizontal action strip beneath the search results — mirrors the
  // `expandedActionsStrip` from InlineAddMaterialRow so the Search & Add tab
  // and the inline-add card on MaterialsListScreen feel like the same UI.
  searchActionsRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 8,
    marginTop: 16,
  },
  searchActionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: t.colors.border,
    backgroundColor: t.colors.surfaceRaised,
  },
  searchActionLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: t.colors.accentText,
  },
  manualSheetFooter: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 8,
  },
  manualSheetButton: {
    borderRadius: 12,
  },
  manualSheetButtonContent: {
    paddingVertical: 6,
  },
}));
